services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      HOSTNAME: 0.0.0.0
      PORT: 3000
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"