packages:
  - .

allowBuilds:
  '@heroui/shared-utils': true
  sharp: true
  supabase: true

ignoredBuiltDependencies:
  - '@vercel/speed-insights'
  - bcrypt
  - sharp

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - supabase
